# This is a basic workflow to help you get started with Actions

name: U-Boot build

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd "1.UBoot"
          curl https://downloads.wdc.com/gpl/WDMyCloud_Ex2Ultra_GPL_v2.31.204_20191206.tar.gz -o WDMyCloud_Ex2Ultra_GPL_v2.31.204_20191206.tar.gz
          tar -xzf WDMyCloud_Ex2Ultra_GPL_v2.31.204_20191206.tar.gz
          mv WDMyCloud_Ex2Ultra_GPL_v2.31.204_20191206/u-boot ./
          mv WDMyCloud_Ex2Ultra_GPL_v2.31.204_20191206/toolchain ./
          rm -rf WDMyCloud_Ex2Ultra_GPL_v2.31.204_20191206
          rm WDMyCloud_Ex2Ultra_GPL_v2.31.204_20191206.tar.gz
          cd toolchain
          tar -xzf armv7-marvell-linux-gnueabi-softfp_i686_64K_Dev_20131002.tar.gz
          cd ../u-boot
          tar -xzf u-boot-2013.01-2014_T3.0p2.tar.gz
          sed -i -e 2,4d u-boot-2013.01-2014_T3.0p2/xbuild.sh
          head u-boot-2013.01-2014_T3.0p2/xbuild.sh
          cd ../toolchain/armv7-marvell-linux-gnueabi-softfp_i686_64K_Dev_20131002/bin
          pewd=$PWD
          cd -
          sed -i "2 a export PATH=\$PATH:$pewd" u-boot-2013.01-2014_T3.0p2/xbuild.sh
          head u-boot-2013.01-2014_T3.0p2/xbuild.sh
          cp ../GrandTeton-20170708.patch u-boot-2013.01-2014_T3.0p2
          cd u-boot-2013.01-2014_T3.0p2
          patch -p1 < GrandTeton-20170708.patch
          sudo apt install gcc-multilib
          whoami
          ./xbuid.sh build
